### PR TITLE
Kubernetes and OpenShift templates for all-in-one distro

### PR DESCRIPTION
**Pull request by pavolloffay**
See https://github.com/uber/jaeger/issues/58

### CODE REVIEW

**Comment by vprithvi** [comment]
LGTM, you might want to add the running instructions to the [documentation](https://github.com/uber/jaeger/blob/master/docs/getting_started.md) to aid discoverability.

**Comment by yurishkuro** [comment]
I don't mind merging this, but my concern with this is how can we ensure that these orchestration files are actually correct? Granted, we have a similar issue with the docker image, but the ticket for it is still open and it had an explicit section about adding tests for each new image. Presumably, the test script would be reusable against another way of running all-in-one like K8s. So is there a way to run these in Travis? At minimum it would be good to check that the process comes up and responds on some endpoints.

**Comment by pavolloffay** [comment]
Could we merge this without tests? @jkandasa and @kevinearls are looking at how to properly test this.

**Comment by black-adder** [comment]
In https://github.com/uber/jaeger/pull/122 I added an integration test that creates a trace and checks if the trace was created for the standalone docker image. Maybe we can do something similar for this? Bring up a kubernetes container in travis and then run the same integration test.

**Comment by pavolloffay** [comment]
An option might be to run it on https://cloud.google.com/container-engine/ and just use `kubectl` to connect there.

**Comment by mattmahoneyrh** [comment]
Yes, https://cloud.google.com/container-engine/ is a possible testing platform. However, there is a prices associated from what I understand. For this reason we set up a Kubernetes cluster in Public OpenStack (OS1) on which we have done testing of Hawkular Services, and can reuse for Jaeger template testing as well (at least for the time being).

**Comment by mattmahoneyrh** [comment]
Testing note:
1) Deployed on OpenShift Enterprise with no issue:
    v3.4.0.40

2) Deployed on Kubernetes with no issue:
    Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ef1caba064de975387860175c3138aad432cf356", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ef1caba064de975387860175c3138aad432cf356", GitTreeState:"clean"}

   Note: kubectl create -f jaeger-all-in-one-kubernetes-template.yaml  --validate=false
     "--validate=false" was needed to successfully deploy.

In both tests, success was the ability to render and then navigate the UI. No data was populated in service.

**Comment by jpkrohling** [comment]
@mattmahoneyrh is your testing note meant to be understood as a guideline for the automation?

**Comment by pavolloffay** [comment]
I'm about to close this. 

OpenShift template has been moved to https://github.com/jaegertracing/jaeger-openshift. Do we want to create a separate repo for k8s templates?

**Comment by yurishkuro** [comment]
might as well. It would be good to add something to documentation about these templates.

**Comment by yurishkuro** [comment]
Just had a look at openshift repo - is there a way to implement some integration tests?

**Comment by objectiser** [comment]
Yes we will be setting up integration tests - just trying to sort out the best environment.

In the meantime: https://github.com/jaegertracing/jaeger-kubernetes has been setup.

**Comment by pavolloffay** [comment]
I will try to do test it with minishift/minikube on travis, if it fails I will give a try with google cloud engine.

**Comment by pavolloffay** [comment]
Closing, templates are in https://github.com/jaegertracing org.

**Pull request closed without merging**
