### PR TITLE
Remove thrift image when it is done

### PR DESCRIPTION
**Pull request by pavolloffay**

### CODE REVIEW

**Comment by yurishkuro** [comment]
what's the objective here?

**Comment by pavolloffay** [comment]
Make thrift leaves a dead container after the run. It should be removed it's not needed.

**Comment by yurishkuro** [comment]
but are you removing the container or the image?  Title says image

**Comment by pavolloffay** [comment]
Wrong title/commit message, it's container

**Comment by yurishkuro** [comment]
cool, thanks

**Pull request merged**
