### PR TITLE
Start http jaeger-collector when starting standalone

### PR DESCRIPTION
**Pull request by vprithvi**

### CODE REVIEW

**Comment by vprithvi** [comment]
>lgtm, but what aer your thoughts on testing it? We could pass an env var to the go-client crossdock image to instruct it to init itself with HTTP sender instead of UDP sender, and run the crossdock test here.

This sounds reasonable for testing jaeger-collector and go-client interop, I'll work on it in a bit. 

Also, it looks like we have no crossdock tests for standalone. My opinion is that we should add some because standalone is the first point of interaction with jaeger for many newcomers, and it would be a bad experience if it's broken.

**Comment by yurishkuro** [comment]
> Also, it looks like we have no crossdock tests for standalone. 

I think the ideal state is to use the same end-to-end test to test both all-in-one and individual deployments.

**Comment by black-adder** [comment]
We do have a standalone integration test that ensures the piping for all-in-one is working. Don't really see the need for putting in extra work to get crossdock tests.

**Comment by black-adder** [comment]
https://github.com/uber/jaeger/blob/master/cmd/standalone/standalone_test.go

**Pull request merged**
