### PR TITLE
Add the packaging metadata to build the jaeger snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest jaeger in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress.

### CODE REVIEW

**Comment by elopio** [comment]
Hello!

Here at Ubuntu we are writing a new packaging and delivery system. You can read more about it here: https://snapcraft.io/

I needed to test a few things in our upcoming release and your project was good for those tests. This, of course, needs more testing, and the other binaries to be exposed in the apps section. But please take a look at the agent, and give it a try to see if you would like to publish it in the ubuntu store.

To test this in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/jaeger
    $ cd jaeger
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous

(`--dangerous` because the snap you build doesn't come signed from the store. Once you push it, all your users will just have to run `$ sudo snap install jaeger`).

**Comment by yurishkuro** [comment]
Jaeger is not an end-user "application", it's a distributed system and we publish multiple Docker images for all of its components.  So how would it be used via snaps?

**Comment by elopio** [comment]
Hello @yurishkuro. The idea of this new package format is that things are very flexible. Upstream developers are who decide how to package, instead of having to adjust to a strong set of rules defined by the distro maintainers. So, you have many options depending on your preference.

You could bundle all your components in a single snap. Then users can install and deploy a simple instance with one click from the software center app. For example, take a look at [nextcloud](https://github.com/nextcloud/nextcloud-snap) that bundles the database, webserver, and nextcloud itself. That of course limits scaling; but most of their users require a single not-to-big server, and this simplicity gives them like 100 new installs every day.

Another option is to make a snap for each component. Then people can deploy three of each in different locations for high-availability, and they can adjust a complex system to their needs. This is for advanced users, because they will have to connect the services.

You could have both. Maybe publish a fat snap called jaeger-full or something, and also publish snaps for jaeger-agent, jaeger-builder, jaeger-collector...

Also, it might be interesting for you that we are enabling snaps to work on docker: https://forum.snapcraft.io/t/snapd-in-docker/177
Then on your Dockerfile you could just put a line with `snap install jaeger-agent`, and that container will take advantage of all the nice features of snaps, like security, automatic updates, rollbacks in case of failure...

Those are just ideas. If you have something else in mind for your perfect delivery solution, I would be very happy to hear about that. We are in active development and looking for new interesting upstreams that will help us define our roadmap. I invite you to give it a try, once you enable your automatic delivery on https://build.snapcraft.io/ the snap will land in the edge channel, where only your contributors and the early adopters from the Ubuntu community will be able to install it. That way you can gather feedback, and see if this gives you value.

pura vida.

**Comment by jpkrohling** [comment]
This looks interesting, but would probably be better suited for a new repository at the `jaegertracing`, alongside with the OpenShift and Kubernetes templates.

**Comment by yurishkuro** [comment]
@jpkrohling agree on the repo location, but I am still not seeing a huge value here given that Docker images is how most people would be deploying Jaeger.

**Comment by elopio** [comment]
Well, this is just a proposal. If you already have all your deployment needs satisfied with Docker, then it doesn't make sense to add more stuff.

I'm biased, of course :) But I see a lot of opportunities with the snap: installable on all the [supported linux distributions](https://snapcraft.io/docs/core/install) with one command, available on the Ubuntu store where the millions of Ubuntu users can find it, automatic updates and rollbacks, four different levels of risk to make the life easier for your early adopters, and a lighter container approach because you don't need a full operating system for every one of your components. And as I said, very easy to give it a try setting it up in http://build.snapcraft.io/. You can check it out, see the stats, ask for feedback to your community, and if things look promising spend more time on it. If not, drop it.

**Comment by jpkrohling** [comment]
I'd vote to close this PR without merging. If we get community demand for Snap packages, then a repo similar to what we have for OpenShift/Kubernetes can be created, potentially from external contributors (and possibly based on this PR!).

**Comment by yurishkuro** [comment]
@jpkrohling +1

I'd also like to apply [the rule of three](https://blog.codinghorror.com/rule-of-three/) when introducing and supporting new features (the method of release packaging is kind of a feature).

**Comment by elopio** [comment]
That is ok. I'll close this PR, and if you get interested later just let me know.

**Pull request closed without merging**
